package handler

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	lmspb "github.com/afnandelfin620-star/cftptest/cftp/glms"
	"google.golang.org/grpc"
)

type externalCoursewareClientStub struct {
	lmspb.LmsServiceClient
	createRequest *lmspb.CreateExternalCoursewareRequest
}

func (s *externalCoursewareClientStub) CreateExternalCoursewareAdmin(
	_ context.Context,
	request *lmspb.CreateExternalCoursewareRequest,
	_ ...grpc.CallOption,
) (*lmspb.ExternalCourseware, error) {
	s.createRequest = request
	return &lmspb.ExternalCourseware{
		CoursewareUlid: request.GetCoursewareUlid(),
		Name:           request.GetName(),
		BaseUrl:        request.GetBaseUrl(),
		TokenParamName: request.GetTokenParamName(),
		Version:        1,
	}, nil
}

func TestCreateExternalCoursewareGeneratesIDAndDefaultsTokenParameter(t *testing.T) {
	client := &externalCoursewareClientStub{}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(
		http.MethodPost,
		"/api/lms/external-coursewares",
		strings.NewReader(`{"courseware_ulid":"web-supplied","name":"Partner Course","base_url":"https://partner.example/view"}`),
	)

	(&Handler{Lms: client}).CreateExternalCourseware(recorder, request)

	if recorder.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d; body=%q", recorder.Code, http.StatusOK, recorder.Body.String())
	}
	if client.createRequest.GetCoursewareUlid() == "" || client.createRequest.GetCoursewareUlid() == "web-supplied" {
		t.Fatalf("courseware ID was not generated by BFF: %q", client.createRequest.GetCoursewareUlid())
	}
	if client.createRequest.GetTokenParamName() != "token" {
		t.Fatalf("token parameter = %q, want token", client.createRequest.GetTokenParamName())
	}
}
