package handler

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	lmspb "github.com/afnandelfin620-star/cftptest/cftp/glms"
	"github.com/go-chi/chi/v5"
	"google.golang.org/grpc"
)

type externalCoursewareClientStub struct {
	lmspb.LmsServiceClient
	createRequest *lmspb.CreateExternalCoursewareRequest
	importRequest *lmspb.ImportCoursewareTokensRequest
}

func (s *externalCoursewareClientStub) ImportCoursewareTokensAdmin(
	_ context.Context,
	request *lmspb.ImportCoursewareTokensRequest,
	_ ...grpc.CallOption,
) (*lmspb.ImportCoursewareTokensResponse, error) {
	s.importRequest = request
	return &lmspb.ImportCoursewareTokensResponse{
		CoursewareUlid: request.GetCoursewareUlid(),
		ImportedCount:  uint32(len(request.GetTokenUrls())),
	}, nil
}

func (s *externalCoursewareClientStub) CreateExternalCoursewareAdmin(
	_ context.Context,
	request *lmspb.CreateExternalCoursewareRequest,
	_ ...grpc.CallOption,
) (*lmspb.ExternalCourseware, error) {
	s.createRequest = request
	return &lmspb.ExternalCourseware{
		CoursewareUlid: request.GetCoursewareUlid(),
		Name:           request.GetName(),
		BaseUrl:        request.GetBaseUrl(),
		Version:        1,
	}, nil
}

func TestCreateExternalCoursewareGeneratesID(t *testing.T) {
	client := &externalCoursewareClientStub{}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(
		http.MethodPost,
		"/api/lms/external-coursewares",
		strings.NewReader(`{"courseware_ulid":"web-supplied","name":"Partner Course","base_url":"https://partner.example/view"}`),
	)

	(&Handler{Lms: client}).CreateExternalCourseware(recorder, request)

	if recorder.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d; body=%q", recorder.Code, http.StatusOK, recorder.Body.String())
	}
	if client.createRequest.GetCoursewareUlid() == "" || client.createRequest.GetCoursewareUlid() == "web-supplied" {
		t.Fatalf("courseware ID was not generated by BFF: %q", client.createRequest.GetCoursewareUlid())
	}
}

func TestImportExternalCoursewareTokensForwardsCompleteURLs(t *testing.T) {
	client := &externalCoursewareClientStub{}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(
		http.MethodPost,
		"/api/lms/external-coursewares/courseware-1/tokens/import",
		strings.NewReader(`{"token_urls":[" https://partner.example/token/one ","https://partner.example/token/two"]}`),
	)
	routeContext := chi.NewRouteContext()
	routeContext.URLParams.Add("courseware_id", "courseware-1")
	request = request.WithContext(context.WithValue(request.Context(), chi.RouteCtxKey, routeContext))

	(&Handler{Lms: client}).ImportExternalCoursewareTokens(recorder, request)

	if recorder.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d; body=%q", recorder.Code, http.StatusOK, recorder.Body.String())
	}
	if got := client.importRequest.GetTokenUrls(); len(got) != 2 || got[0] != "https://partner.example/token/one" || got[1] != "https://partner.example/token/two" {
		t.Fatalf("token URLs = %#v", got)
	}
}
