export const adminPageChecks = [
  { path: "/dashboard", endpoint: "/api/dashboard/ops" },
  { path: "/resource-packs", endpoint: "/api/lms/resource-packs" },
  { path: "/resource-pack-files", endpoint: "/api/lms/resource-pack-files" },
  { path: "/lms", endpoint: "/api/lms/courses" },
  { path: "/pipelines", endpoint: "/api/pipelines" },
  { path: "/bundles", endpoint: "/api/mall/bundles" },
  { path: "/memberships", endpoint: "/api/memberships/configs" },
  { path: "/prog", endpoint: "/api/prog/pipelines" },
  { path: "/exams", endpoint: "/api/exams" },
  { path: "/messages", endpoint: "/api/messages/templates" },
  { path: "/mails", endpoint: "/api/mails/templates" },
  { path: "/orders", endpoint: "/api/mall/orders" },
  { path: "/invoices", endpoint: "/api/mall/invoices" },
  { path: "/credentials", endpoint: "/api/credentials/definitions" },
  { path: "/applications", endpoint: "/api/applications" },
  { path: "/pdf-templates", endpoint: "/api/pdf-templates" },
  { path: "/pdf-requests", endpoint: "/api/pdf-requests" },
  { path: "/admin-ops", endpoint: "/api/pay/subscriptions" },
  { path: "/audit/logs", endpoint: "/api/audit/logs" },
  { path: "/audit/webhooks", endpoint: "/api/audit/webhooks" },
  { path: "/permissions", endpoint: "/api/credentials/definitions" },
  { path: "/settings", endpoint: "/api/user/me" },
] as const
